### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by KaTaiHo** [mohdumar644/TinyYOLO-BNN#2]
Hi, 

I came to your github since someone recommended it from https://github.com/Xilinx/QNN-MO-PYNQ/issues/35. I was wondering how I would export the weights such that I could use them for the QNN-MO-PYNQ tinier yolo. I've followed all the sets on your GitHub but I don't know what to do with the bin files and the .npz files.

It seems like for the deployment you meant we should copy over the bin files and place them under QNN-MO-PYNQ/qnn/params/binparam-dorefanet/ and then use Vivado to recompile it is this correct?

Additionally, do you happen to have the gen-weights file for converting for QNN-MO-PYNQ?

Thanks!

**Comment by mohdumar644** [comment]
I did try loading custom weights for the QNN-MO-PYNQ tinier yolo, a few months back.
It was not so simple as the .bin file generation involved several technicalities, some of which I could not figure out as Xilinx had not provided their own Finnthesizer (I did discover the 'split' mechanism of evaluating 512 output feature maps by two successive runs of 256 ofms, and packing thresholds and invert bits in a specific manner, but the weight matrix padding for certain layers caused confusion) 

I suggest sticking to this repo as it is much simpler and straightforward. Of course you can edit it to have FP32 initial and final convolutional layers, as well as using the Darknet shared object instead of custom postprocessing.
